# Generated by Django 5.1.1 on 2024-10-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cuisine', models.CharField(blank=True, max_length=100, null=True)),
                ('DishName', models.CharField(blank=True, max_length=100, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('About', models.TextField(blank=True, max_length=100, null=True)),
                ('CuisineImage', models.ImageField(blank=True, null=True, upload_to='Cuisine')),
            ],
        ),
    ]
