# Generated by Django 5.1.1 on 2024-10-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_dishdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishdb',
            name='CuisineImage',
        ),
        migrations.AddField(
            model_name='dishdb',
            name='DishImage',
            field=models.ImageField(blank=True, null=True, upload_to='Dish'),
        ),
    ]
